In [3]:
import numpy as np

In [9]:
a = np.arange(10)*10

In [10]:
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [11]:
a[2]

20

In [12]:
a[1], a[2]

(10, 20)

In [14]:
a[[1,2]]

array([10, 20])

In [18]:
np.random.seed()
a = np.random.randint(0, 21, 15)
a

array([17,  3, 15,  1, 18, 20,  8, 20,  4,  3, 11,  0,  9,  1,  7])

In [19]:
a % 3 == 0

array([False,  True,  True, False,  True, False, False, False, False,
        True, False,  True,  True, False, False])

In [20]:
a[a%3 == 0]

array([ 3, 15, 18,  3,  0,  9])

In [21]:
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
a[:,0]

array([1., 0., 0., 0., 0.])

In [30]:
a = np.arange(10)
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [32]:
np.may_share_memory(a, b)

True

In [33]:
b[0] = 12
b

array([12,  2,  4,  6,  8])

In [34]:
a   # (!)

array([12,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [35]:
a = np.arange(10)
c = a[::2].copy()  # force a copy
c[0] = 12
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.may_share_memory(a, c)

False