**1- Import the numpy package under the name np**

In [1]:
import numpy as np

**2 - Print the numpy version and the configuration**

In [2]:
np.__version__

'1.16.5'

In [3]:
np.show_config()

mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['P:/Programas/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'P:/Programas/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['P:/Programas/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'P:/Program

**3 - Create a null vector of size 10**

In [4]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**4 - How to find the memory size of any array**

In [5]:
a.size

10

**5 - How to get the documentation of the numpy add function from the command line?**

In [6]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

**6 - Create a null vector of size 10 but the fifth value which is 1**

In [7]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

**7 - Create a vector eith values ranging from 10 to 49**

In [8]:
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

**8 - Reverse a vector (first element becomes last)**

In [9]:
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

**9 - Create a 3x3 matrix with values ranging from 0 to 8**

In [10]:
a = np.arange(9).reshape((3,3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**10 - Find indices of non-zero elements from [1, 2, 0, 0, 4, 0]**

In [11]:
a = np.array([1, 2, 0, 0, 4, 0]).nonzero()
a

(array([0, 1, 4], dtype=int64),)

**11 - Create a 3x3 identity matrix**

In [12]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**12 - Create a 3x3x3 array with random values**

In [13]:
a = np.random.random((3,3,3))
a

array([[[0.54249021, 0.32108656, 0.93018715],
        [0.09216457, 0.31550517, 0.85556812],
        [0.02623528, 0.85946838, 0.71187107]],

       [[0.80306403, 0.18104072, 0.22762691],
        [0.42019149, 0.35403774, 0.78270996],
        [0.43539916, 0.5623649 , 0.82909263]],

       [[0.84426867, 0.23114484, 0.65820561],
        [0.46923859, 0.61429485, 0.9597216 ],
        [0.64233405, 0.48260622, 0.5853112 ]]])

**13 -  Create a 10x10 array with random values and find the minimum and maximum values**

In [14]:
a = np.random.rand(10,10)
a

array([[0.41634152, 0.9677796 , 0.18472702, 0.83086487, 0.15895904,
        0.03799326, 0.7615383 , 0.26900006, 0.16351703, 0.91346141],
       [0.73246281, 0.54693695, 0.18730051, 0.22896176, 0.92052449,
        0.65833662, 0.61817479, 0.59649203, 0.94742254, 0.31081248],
       [0.9299943 , 0.70435141, 0.88884512, 0.99912765, 0.47148536,
        0.9553282 , 0.01206591, 0.14100013, 0.67643551, 0.5690008 ],
       [0.76019742, 0.62895899, 0.73018288, 0.37569384, 0.49481314,
        0.88678476, 0.02382816, 0.0492072 , 0.40009531, 0.87799495],
       [0.97791634, 0.93234387, 0.96509348, 0.92138412, 0.1536204 ,
        0.41784371, 0.24867673, 0.17762677, 0.88817197, 0.71265732],
       [0.06680916, 0.77731079, 0.72835251, 0.80627581, 0.87659901,
        0.61146726, 0.39753174, 0.9711506 , 0.71972773, 0.03085888],
       [0.31281503, 0.47655324, 0.16730342, 0.03507437, 0.72312832,
        0.24633612, 0.7844809 , 0.07064801, 0.42447007, 0.79198548],
       [0.88900974, 0.45956862, 0.3423172

In [15]:
print("Menor valor: ", a.min(), "\n", "Maior valor: ", a.max())

Menor valor:  0.012065914442334402 
 Maior valor:  0.9991276541140529


**14 -  Create a random vector of size 30 and find the mean value**

In [16]:
a = np.random.random(30)
a

array([0.51526873, 0.90586236, 0.18578035, 0.24810331, 0.91964432,
       0.14639409, 0.36059034, 0.68963819, 0.32730748, 0.30948728,
       0.23434413, 0.60112457, 0.06549632, 0.82638519, 0.98686359,
       0.69651746, 0.36231281, 0.92766959, 0.68684253, 0.16233513,
       0.11916989, 0.89264317, 0.5311215 , 0.9725267 , 0.57243108,
       0.88724744, 0.37405863, 0.90589061, 0.19294725, 0.72080828])

In [17]:
print("Valor médio: ", a.mean())

Valor médio:  0.5442270770758445


**15 - Create a 2d array with 1 on the border and 0 inside**

In [18]:
a = np.ones((10, 10))
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [19]:
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

**16 - How to add a border (filled with 0's) around an existing array?** 

In [20]:
a = np.zeros((10,10))
a[1:-1, 1:-1] = 1
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

**17 - Qual é o resultado da seguinte expressão?**

In [21]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


**18 - Create a 5x5 matrix with values 1,2,3,4 just below the diagonal**

In [22]:
a = np.diag(1+np.arange(4),k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


**19 - Create a 8x8 matrix and fill it with a checkerboard pattern**

In [23]:
a = np.zeros((8,8),dtype=int)
for i in range(len(a)):
    for j in range(len(a)):
        if i % 2 == 0 and j % 2 == 0:
            a[i][j] = 1
        elif i % 2 != 0 and j % 2 != 0:
            a[i][j] = 1
a

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

**20 - Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?**

In [24]:
a = np.unravel_index(99,(6,7,8))
a

(1, 5, 3)

**21 - Create a checkerboard 8x8 matrix using the tile function**

In [25]:
a = np.tile( np.array([[0,1],[1,0]]), (4,4))
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

**22 - Normalize a 5x5 random matriz**

In [26]:
a = np.random.random((5,5))
a = (a - np.mean (a)) / (np.std (a))
a

array([[-7.97448316e-01, -2.65404035e-01,  9.00589667e-04,
         5.77808583e-01,  6.77352428e-01],
       [-1.29784202e+00, -7.44691665e-01,  1.57884175e-01,
         3.88492138e-01, -1.06960955e-01],
       [ 1.69938139e+00,  1.25510037e+00, -5.60304658e-01,
        -1.25816067e+00,  4.96310517e-01],
       [-3.22498016e-03,  1.51159815e+00, -1.17787851e+00,
        -1.15169966e+00,  1.90083261e+00],
       [-1.28679337e+00, -5.43377680e-01,  1.37110774e+00,
        -1.33528789e+00,  4.92305725e-01]])

**23 - Create a custom dtype that describes a color as four unsigned bytes (RGBA)**

**24 - Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)** 

In [27]:
a = np.dot(np.ones((5,3)), np.ones((3,2)))
a

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

**25 - Given a 1D array, negate all elements which are between 3 and 8, in place.**

In [28]:
a = np.arange(11)
a[(3 < a) & (a <= 8)] *= -1
a

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

**26 - What is the output of the following script?**

In [29]:
np.array(0) / np.array(0)

P:\Programas\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [30]:
np.array(0) // np.array(0)

P:\Programas\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [31]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

**27 - Consider an integer vector Z, which of these expressions are legal?**

In [32]:
Z = np.arange(10)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)


[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
[  0   1   2   4   8  16  32  64 128 256]
[False False False False False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


**28 - What are the result of the following expressions?**

In [33]:
np.array(0) / np.array(0)

P:\Programas\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [34]:
np.array(0) // np.array(0)

P:\Programas\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [35]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

**29 - How to round away from zero a float array?**

In [36]:
a = np.random.uniform(-10,+10,10)
a

array([-6.38563652,  6.87305944, -4.70133635, -2.96450313, -0.93075151,
       -1.54782511,  9.77760314, -1.38037583,  9.89699382, -4.37132307])

In [37]:
np.copysign(np.ceil(np.abs(a)), a)

array([-7.,  7., -5., -3., -1., -2., 10., -2., 10., -5.])

**30 - How to find common values between two arrays?**

In [38]:
a = np.random.randint(0,10,5)
b = np.random.randint(0,10,5)
print(np.intersect1d(a,b))

[4 5 8]


**31 - How to ignore all numpy warnings (not recommended)?**

In [39]:
defaults = np.seterr(all="ignore")
print(np.array([np.nan]).astype(int).astype(float))

_ = np.seterr(**defaults)

[-2.14748365e+09]


**32 - Is the following expressions true?** 

In [40]:
print(np.sqrt(-1) == np.emath.sqrt(-1))
print(np.emath.sqrt(-1))
print(np.sqrt(-1))

False
1j
nan


P:\Programas\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.
P:\Programas\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in sqrt
  This is separate from the ipykernel package so we can avoid doing imports until


 **33 - How to get the dates of yesterday, today and tomorrow?**

In [41]:
today = np.datetime64('today', 'D')
yesterday = today - 1
tomorow = today + 1
print(yesterday)
print(today)
print(tomorow) 

2020-02-17
2020-02-18
2020-02-19


**34 - How to get all the dates corresponding to the month of July 2016?**

In [42]:
np.arange('2016-06', '2016-07',  dtype='datetime64[D]')

array(['2016-06-01', '2016-06-02', '2016-06-03', '2016-06-04',
       '2016-06-05', '2016-06-06', '2016-06-07', '2016-06-08',
       '2016-06-09', '2016-06-10', '2016-06-11', '2016-06-12',
       '2016-06-13', '2016-06-14', '2016-06-15', '2016-06-16',
       '2016-06-17', '2016-06-18', '2016-06-19', '2016-06-20',
       '2016-06-21', '2016-06-22', '2016-06-23', '2016-06-24',
       '2016-06-25', '2016-06-26', '2016-06-27', '2016-06-28',
       '2016-06-29', '2016-06-30'], dtype='datetime64[D]')

**35 - How to compute ((A+B)*(-A/2)) in place (without copy)?**

In [43]:
A = np.ones(3)*1
print(A)
B = np.ones(3)*2
print(B)
C = np.ones(3)*3
print(C)
print(np.add(A,B,out=B))
print(np.divide(A,2,out=A))
print(np.negative(A,out=A))
print(np.multiply(A,B,out=A))

[1. 1. 1.]
[2. 2. 2.]
[3. 3. 3.]
[3. 3. 3.]
[0.5 0.5 0.5]
[-0.5 -0.5 -0.5]
[-1.5 -1.5 -1.5]


**36 - Extract the integer part of a random array using 5 different methods**

In [44]:
a = np.random.uniform(0,10,10)

print (a - a%1)
print (np.floor(a))
print (np.ceil(a)-1)
print (a.astype(int))
print (np.trunc(a))

[7. 1. 6. 5. 7. 7. 8. 1. 8. 1.]
[7. 1. 6. 5. 7. 7. 8. 1. 8. 1.]
[7. 1. 6. 5. 7. 7. 8. 1. 8. 1.]
[7 1 6 5 7 7 8 1 8 1]
[7. 1. 6. 5. 7. 7. 8. 1. 8. 1.]


**37 - Create a 5x5 matrix with row values ranging from 0 to 4**

In [45]:
a = np.zeros((5,5))
a += np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


**38 - Consider a generator function that generates 10 integers and use it to build an array**

In [46]:
def generate():
    for x in range(10):
        yield x
a = np.fromiter(generate(),dtype=float,count=-1)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


**39 - Create a vector of size 10 with values ranging from 0 to 1, both excluded**

In [47]:
np.linspace(0,1,11,endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

**40- Create a random vector of size 10 and sort it**

In [48]:
a = np.random.random(10)
print(a, "\n")
a.sort()
print(a)

[0.7919168  0.95246243 0.85070736 0.09784682 0.46497425 0.83283432
 0.3980276  0.7359505  0.28800103 0.05208227] 

[0.05208227 0.09784682 0.28800103 0.3980276  0.46497425 0.7359505
 0.7919168  0.83283432 0.85070736 0.95246243]


**41 - How to sum a small array faster than np.sum?**

In [49]:
a = np.arange(4)
np.add.reduce(a)

6

**42 - Consider two random array A and B, check if they are equal**

In [50]:
a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)

equal = np.allclose(a,b)
print(equal)

equal = np.array_equal(a,b)
print(equal)

True
True


**43 - Make an array immutable (read-only)**

In [51]:
x = np.zeros(10)
x.flags.writeable = False
x[0] = 1

ValueError: assignment destination is read-only

Mensagem de erro relativo a tentativa de mudança de um array somente leitura

**44 - Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates** 

In [61]:
Z = np.random.random((10,2))

X,Y = Z[:,0], Z[:,1]

R = np.sqrt(X**2+Y**2)

T = np.arctan2(Y,X)

print(R)

print(T)

[0.62263364 0.32788043 0.93984231 1.23221483 0.8963745  0.91191919
 0.9864862  0.92568477 0.88656302 1.06187378]
[1.26715168 1.56387782 0.51384215 0.786645   1.06071045 1.22275673
 0.77306335 0.70602613 1.16201778 0.63781624]


**45 - Create random vector of size 10 and replace the maximum value by 0**

In [62]:
a = np.random.random(10)

print(a)

print(a.argmax()) 
a[a.argmax()] = 0

print(a)

[0.5991716  0.01155825 0.74727713 0.4220698  0.49155846 0.76959962
 0.85736039 0.12938221 0.92303557 0.99634267]
9
[0.5991716  0.01155825 0.74727713 0.4220698  0.49155846 0.76959962
 0.85736039 0.12938221 0.92303557 0.        ]


**46 - Create a structured array with x and y coordinates covering the [0,1]x[0,1] area**

In [ ]:
a = np.zeros((5,5), [('x',float),('y',float)])

a['x'], a['y'] = np.meshgrid(np.linspace(0,1,5),

np.linspace(0,1,5))

print(a)

**47 - Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))**

In [63]:
X = np.arange(8)

Y = X + 0.5

C = 1.0 / np.subtract.outer(X, Y)

print(np.linalg.det(C))

3638.1636371179666


**48 - Print the minimum and maximum representable value for each numpy scalar type**

In [67]:
for dtype in [np.int8, np.int32, np.int64]:

    print(np.iinfo(dtype).min)

    print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:

    print(np.finfo(dtype).min)

    print(np.finfo(dtype).max)

    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


**49 - How to print all the values of an array?**

In [68]:
np.set_printoptions(threshold=np.nan)
a = np.zeros((16,16))
print(a)

ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation

**50 - How to find the closest value (to a given scalar) in a vector?** 

In [69]:
x = np.arange(100)
print(x)
a = np.random.uniform(0,100)
print("Value to compare:")
print(a)
index = (np.abs(x-a)).argmin()
print(x[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Value to compare:
99.14720958606094
99


**51 - Create a structured array representing a position (x,y) and a color (r,g,b)**

In [72]:
a = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(a)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


**52 - Consider a random vector with shape (100,2) representing coordinates, find point by point distances**

In [73]:
Z = np.random.random((10,2))
print(Z)
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

import scipy
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.29000708 0.56152498]
 [0.19384824 0.03356253]
 [0.12405047 0.07277715]
 [0.95972934 0.81554951]
 [0.38142989 0.91850638]
 [0.14237614 0.88420553]
 [0.02213341 0.03148961]
 [0.79044502 0.29901048]
 [0.52028077 0.95324654]
 [0.48972005 0.70163231]]
[[0.         0.53664781 0.51615506 0.71627953 0.36850217 0.35484874
  0.59388029 0.56511237 0.45439163 0.24395765]
 [0.53664781 0.         0.08005944 1.09456726 0.90460626 0.85219885
  0.17172734 0.65298571 0.97589799 0.73065543]
 [0.51615506 0.08005944 0.         1.11806527 0.88402607 0.8116353
  0.10996249 0.7037494  0.9655179  0.72744282]
 [0.71627953 1.09456726 1.11806527 0.         0.58739286 0.82023161
  1.22222586 0.54357129 0.46051658 0.48361747]
 [0.36850217 0.90460626 0.88402607 0.58739286 0.         0.24150205
  0.95702284 0.74233991 0.14313087 0.24240693]
 [0.35484874 0.85219885 0.8116353  0.82023161 0.24150205 0.
  0.861152   0.87318183 0.38415956 0.39240384]
 [0.59388029 0.17172734 0.10996249 1.22222586 0.95702284 0.861152
  


**53 - How to convert a float (32 bits) array into an integer (32 bits) in place?**

In [76]:
A = np.arange(10, dtype=np.float32)
A = A.astype(np.int32, copy=False)
print(A)

[0 1 2 3 4 5 6 7 8 9]


**54 - How to read the following file?**

In [81]:
from io import StringIO

s = StringIO("""1, 2, 3, 4, 5\n
                6,  , 0 , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1  0  7  8]
 [-1 -1  9 10 11]]


**55 - What is the equivalent of enumerate for numpy arrays?**

In [84]:
a = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(a):
    print(index, value)
for index in np.ndindex(a.shape):
    print(index, a[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


**56 - Generate a generic 2D Gaussian-like array**

In [87]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
A = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(A)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

**57 - How to randomly place p elements in a 2D array?**

In [88]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]


**58. Subtract the mean of each row of a matrix**

In [91]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
Y = X - X.mean(axis=1).reshape(-1, 1)
print(Y)

[[-0.04246313  0.21963056  0.13382943 -0.30753132 -0.44492059 -0.33150362
   0.41629765  0.30918925 -0.16867265  0.21614443]
 [-0.33134663  0.51960082  0.22399149 -0.37050728 -0.26441948 -0.17342607
   0.48455565  0.33580791 -0.09868454 -0.32557189]
 [ 0.38643144 -0.34303748  0.39788833 -0.25582017  0.0311996  -0.03942065
   0.07305205  0.15850345 -0.29315357 -0.11564299]
 [ 0.68823427  0.08444726 -0.2166331  -0.20670658 -0.24801915 -0.1234172
   0.00137387  0.07417638 -0.07195548  0.01849972]
 [-0.06792184  0.1933733  -0.19843544 -0.33472747  0.62438123 -0.16779744
  -0.14554358  0.06283303 -0.09939301  0.13323122]]


**59. How to sort an array by the nth column?**

In [93]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[1 8 6]
 [7 1 0]
 [7 7 4]]
[[7 1 0]
 [7 7 4]
 [1 8 6]]


**60. How to tell if a given 2D array has null columns?**

In [96]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


**61. Find the nearest value from a given value in an array**

In [99]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.4269536069578348


**62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?**

In [102]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


**63. Create an array class that has a name attribute**

In [105]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


**64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?**

In [110]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)

[2. 2. 5. 4. 3. 2. 4. 3. 3. 2.]
[3. 3. 9. 7. 5. 3. 7. 5. 5. 3.]


**65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?**

In [113]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


**66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors**

In [116]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


**67. Considering a four dimensions array, how to get sum over the last two axis at once?**

In [119]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[38 39 59 73]
 [50 63 61 37]
 [62 55 62 60]]
[[38 39 59 73]
 [50 63 61 37]
 [62 55 62 60]]


**68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices?**

In [121]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)


import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.41234438 0.4365562  0.44433662 0.61629923 0.45658257 0.5474951
 0.67469127 0.54132842 0.44556352 0.5804514 ]
0    0.412344
1    0.436556
2    0.444337
3    0.616299
4    0.456583
5    0.547495
6    0.674691
7    0.541328
8    0.445564
9    0.580451
dtype: float64


**69. How to get the diagonal of a dot product?**

In [122]:

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

  
print(np.diag(np.dot(A, B)))

print(np.sum(A * B.T, axis=1))

np.einsum("ij,ji->i", A, B)

[1.50644993 1.01889075 2.70065571 0.65450881 1.94319158]
[1.50644993 1.01889075 2.70065571 0.65450881 1.94319158]


array([1.50644993, 1.01889075, 2.70065571, 0.65450881, 1.94319158])

**70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?**

In [123]:
a = np.array([1,2,3,4,5])

a0 = np.zeros(len(a) + (len(a)-1)*(3))
a0[::3+1] = a
print(a0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


**71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?**

In [126]:
a = np.ones((5,5,3))
b = 2*np.ones((5,5))
print(a * b[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


**72. How to swap two rows of an array?**

In [128]:
a = np.arange(25).reshape(5,5)
a[[0,1]] = a[[1,0]]
a

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles**

In [129]:

faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 5, 49) ( 5, 77) ( 7, 72) ( 7, 81) (15, 16) (15, 82) (16, 30) (16, 31)
 (16, 82) (20, 39) (20, 55) (25, 43) (25, 68) (27, 67) (27, 96) (30, 31)
 (38, 72) (38, 95) (39, 55) (43, 53) (43, 55) (43, 68) (49, 77) (53, 55)
 (58, 82) (58, 83) (67, 96) (72, 81) (72, 95) (82, 83)]


**74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C?**

In [130]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


**75. How to compute averages using a sliding window over an array?**

In [131]:

def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


**76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])**

In [132]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


**77. How to negate a boolean, or to change the sign of a float inplace?**

In [133]:

a = np.random.randint(0,2,100)
print(np.logical_not(a, out=a))

a = np.random.uniform(-1.0,1.0,100)
print(np.negative(a, out=a))

[1 0 0 0 1 0 0 1 0 0 1 1 1 0 0 1 0 1 0 1 1 1 0 1 0 0 1 0 1 1 1 0 1 0 1 1 1
 0 1 0 1 1 0 0 1 0 0 1 0 1 1 1 0 1 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 1 1 1 1
 1 1 1 0 0 0 0 1 0 1 0 0 1 0 1 1 1 0 1 1 0 0 0 1 1 1]
[-0.36796082 -0.38124114  0.28910816 -0.12711341 -0.20839807 -0.34515246
 -0.33469907  0.58679726  0.50985396 -0.01964094 -0.9484492  -0.72199966
  0.74550336 -0.46578363 -0.32795973 -0.9442732  -0.89839328 -0.03326764
 -0.79613913  0.11017702 -0.92509281  0.68890158  0.71944805  0.71497314
  0.8281101  -0.69222513 -0.2156586  -0.7348938   0.26099023  0.13204674
  0.52451179  0.05630038  0.2636044   0.443841    0.37668194 -0.18430364
  0.07668658  0.2670592  -0.150694   -0.53706034 -0.21745376  0.27035903
 -0.82228279  0.83644316 -0.72784238  0.33149279  0.22610035  0.82771732
 -0.72016064  0.12532062  0.8968677   0.59484391 -0.43373673  0.87716217
 -0.42499486  0.05800173 -0.30483583 -0.36973754  0.7419331  -0.9642278
  0.20655307 -0.83512303 -0.35321303  0.08720562  0.04396565 -0.998

**78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?**

In [134]:

def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 5.98414314  0.99648942  3.66749672  4.34435552  2.1166448   4.05021261
  8.12763771  4.28039655  0.61549525 10.58787181]


**79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?**

In [135]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 5.90662614  6.20776233 12.66012277 13.63559256  0.37698365  3.24161899
  10.29843814 10.05925864  7.53224136  5.29336704]
 [12.86391752  7.08038798 17.21848125  9.12895638  5.21292633  3.34555274
   3.96790735  6.39213769  0.87047724  0.77395269]
 [ 3.85132707  1.14294883  2.21217039 14.29395638 11.13795175 13.67353639
  15.23763785  9.15443643 17.88055206  5.97686136]
 [ 3.99383119  5.89127907 11.3562036  14.80385413  1.9503419   5.06756581
  11.98967968 10.99188853  9.37634383  6.46523185]
 [ 8.9050315   7.32596106 15.11577604 12.37922438  2.38590857  0.25821185
   8.0473516   9.21142036  4.53948615  4.03061867]
 [14.3021506   5.77371566  9.53478003  3.84920165  0.15454948  2.1690617
   5.72226282  7.23308139  1.63110579 12.19151119]
 [10.78321563  2.68484451 13.1190316   6.65556104  1.57008927  0.57041563
   3.20253505  3.40737171  3.54090133  1.6907566 ]
 [11.47591411  5.42089661 15.32605962  8.65523357  3.38958502  1.7421371
   4.27572122  5.65741293  2.44314025  0.30452681]
 [

**80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary)**

In [136]:

Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[5 2 1 3 1 4 6 0 8 8]
 [1 3 4 0 9 3 4 1 8 7]
 [9 5 0 9 9 5 5 2 4 8]
 [2 9 6 6 4 6 3 0 2 9]
 [2 7 5 4 4 7 1 1 8 7]
 [8 0 9 6 6 0 8 7 9 4]
 [4 1 1 6 3 3 5 4 8 5]
 [0 0 4 3 0 2 6 2 1 2]
 [7 0 8 7 1 6 5 4 3 9]
 [1 1 2 4 3 3 5 0 3 7]]
[[0 0 0 0 0]
 [0 5 2 1 3]
 [0 1 3 4 0]
 [0 9 5 0 9]
 [0 2 9 6 6]]


P:\Programas\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


**81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?**

In [137]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


**82. Compute a matrix rank**

In [138]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) 
rank = np.sum(S > 1e-10)
print(rank)

10


**83. How to find the most frequent value in an array?**

In [140]:
Z = np.random.randint(0,10,50)
print(Z)
print(np.bincount(Z).argmax())

[3 1 7 5 4 9 1 4 3 1 4 1 8 7 8 6 1 5 8 8 0 3 6 2 6 7 2 1 6 8 7 0 9 1 8 7 4
 9 4 5 4 6 3 4 8 8 6 8 3 9]
8


**84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix**

In [143]:

Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[0 3 2]
   [1 1 2]
   [0 0 2]]

  [[3 2 2]
   [1 2 1]
   [0 2 2]]

  [[2 2 4]
   [2 1 3]
   [2 2 1]]

  [[2 4 4]
   [1 3 1]
   [2 1 2]]

  [[4 4 3]
   [3 1 0]
   [1 2 2]]

  [[4 3 0]
   [1 0 2]
   [2 2 3]]

  [[3 0 0]
   [0 2 1]
   [2 3 4]]

  [[0 0 2]
   [2 1 3]
   [3 4 4]]]


 [[[1 1 2]
   [0 0 2]
   [1 4 1]]

  [[1 2 1]
   [0 2 2]
   [4 1 1]]

  [[2 1 3]
   [2 2 1]
   [1 1 0]]

  [[1 3 1]
   [2 1 2]
   [1 0 4]]

  [[3 1 0]
   [1 2 2]
   [0 4 2]]

  [[1 0 2]
   [2 2 3]
   [4 2 3]]

  [[0 2 1]
   [2 3 4]
   [2 3 4]]

  [[2 1 3]
   [3 4 4]
   [3 4 4]]]


 [[[0 0 2]
   [1 4 1]
   [1 4 0]]

  [[0 2 2]
   [4 1 1]
   [4 0 3]]

  [[2 2 1]
   [1 1 0]
   [0 3 2]]

  [[2 1 2]
   [1 0 4]
   [3 2 3]]

  [[1 2 2]
   [0 4 2]
   [2 3 0]]

  [[2 2 3]
   [4 2 3]
   [3 0 0]]

  [[2 3 4]
   [2 3 4]
   [0 0 0]]

  [[3 4 4]
   [3 4 4]
   [0 0 1]]]


 [[[1 4 1]
   [1 4 0]
   [2 4 1]]

  [[4 1 1]
   [4 0 3]
   [4 1 4]]

  [[1 1 0]
   [0 3 2]
   [1 4 0]]

  [[1 0 4]
   [3 2 3]
   [4 0 4]]

  [[0 4 2]
   

**85. Create a 2D array subclass such that Z[i,j] == Z[j,i]**

In [146]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 0  7 15  9 13]
 [ 7  1 10  6  6]
 [15 10  9 42  9]
 [ 9  6 42  3  7]
 [13  6  9  7  3]]


**86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))**

In [148]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


**87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?**

In [151]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


**88. How to implement the Game of Life using numpy arrays?**

In [154]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


**89. How to get the n largest values of an array**

In [157]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argsort(Z)[-n:]])
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9997 9995 9996 9998 9999]


**90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item)**

In [160]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


**91. How to create a record array from a regular array?**

In [163]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


**92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods**

In [ ]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)
print(x)

**93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?**

In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

**94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])**

In [58]:
Z = np.random.randint(0,5,(10,3))
print(Z)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[0 3 3]
 [0 3 3]
 [0 3 4]
 [1 0 4]
 [4 3 0]
 [0 4 2]
 [3 2 1]
 [0 0 3]
 [0 1 4]
 [0 2 1]]
[[0 3 3]
 [0 3 3]
 [0 3 4]
 [1 0 4]
 [4 3 0]
 [0 4 2]
 [3 2 1]
 [0 0 3]
 [0 1 4]
 [0 2 1]]
[[0 3 3]
 [0 3 3]
 [0 3 4]
 [1 0 4]
 [4 3 0]
 [0 4 2]
 [3 2 1]
 [0 0 3]
 [0 1 4]
 [0 2 1]]


**95. Convert a vector of ints into a matrix binary representation**

In [57]:

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])


I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


**96. Given a two dimensional array, how to extract unique rows?**

In [56]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

# Author: Andreas Kouzelis
# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 1 0]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]
[[0 1 0]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


**97 - Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function**

In [55]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[6.28873211e-01, 5.34447320e-02, 5.66920322e-02, 1.22678302e-01,
        2.23271087e-01, 8.02664442e-01, 2.06342449e-01, 1.61542805e-01,
        7.43090327e-01, 7.08608502e-01],
       [5.02682731e-03, 4.27204456e-04, 4.53161385e-04, 9.80615213e-04,
        1.78469233e-03, 6.41600797e-03, 1.64937517e-03, 1.29127425e-03,
        5.93980898e-03, 5.66418239e-03],
       [5.00538412e-01, 4.25382109e-02, 4.51228312e-02, 9.76432154e-02,
        1.77707928e-01, 6.38863888e-01, 1.64233935e-01, 1.28576599e-01,
        5.91447124e-01, 5.64002040e-01],
       [6.63904851e-01, 5.64218926e-02, 5.98500850e-02, 1.29512147e-01,
        2.35708495e-01, 8.47377193e-01, 2.17836840e-01, 1.70541613e-01,
        7.84484478e-01, 7.48081828e-01],
       [3.08145213e-01, 2.61876926e-02, 2.77788560e-02, 6.01118490e-02,
        1.09401888e-01, 3.93302182e-01, 1.01106927e-01, 7.91552909e-02,
        3.64111117e-01, 3.47215169e-01],
       [3.17129340e-01, 2.69512078e-02, 2.85887623e-02, 6.18644398e-02,
   

**98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples**

In [54]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

**99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.**

In [52]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


**100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).**

In [53]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.184942    0.20328172]
