In [6]:
import scipy.linalg as sla
import numpy as np

### Exercício 1.
* Verifique, refazendo o exemplo acima, se a equação da substituição retroativa, descrita na equação 20, de fato funciona.


In [30]:
A = np.array([[3, 4, -5, 1],[0, 1, 1, -2],[0, 0, 4, -5],[0, 0, 0, 2]])
b = np.array([-10, -1, 3, 2])

In [31]:
sla.solve_triangular(A,B)

array([ 1., -1.,  2.,  1.])

Funciona!

### Exercício 2.
* Faça um programa em Python que calcule a solução de um sistema triangular superior usando substituição retroativa. Para representação das matrizes e vetores use exclusivamente Numpy.

In [32]:
def SubstituicaoRetroativa(A, b):
    n = np.size(b)
    x = np.zeros(n)

    for i in range(n-1, -1, -1):
        soma = 0
        for j in range(i + 1, n):
            soma += A[i][j] * x[j]
        x[i] = (b[i] - soma) / A[i][i]
    return x

A = np.array([[3, 4, -5, 1],[0, 1, 1, -2],[0, 0, 4, -5],[0, 0, 0, 2]])
b = np.array([-10, -1, 3, 2])
print(SubstituicaoRetroativa(A, b))

[ 1. -1.  2.  1.]


### Exercício 3.

* Faça um programa em Python que calcule a solução de um sistema triangular inferior usando substituição progressiva. Para representação das matrizes e vetores use exclusivamente Numpy

In [20]:
def SubstituicaoProgressiva(a, b):
    n = np.size(b)
    x = np.zeros(n)
    for i in range(n):
        soma = 0
        for j in range(n - 1, -1, -1):
            soma += a[i][j] * x[j]

        x[i] = (b[i] - soma) / a[i][i]
    return x



A = np.array([[3, 0, 0, 0], [2, 1, 0, 0], [1, 0, 1, 0], [1, 1, 1, 1]])
b = np.array([4, 2, 4, 2])
print(SubstituicaoProgressiva(A, b))

[ 1.33333333 -0.66666667  2.66666667 -1.33333333]


### Exercício 4. 
* Compare os resultados das implementações de suas funções para a solução de sistemas triangulares com a função do scipy. Os resultados são diferentes? Experimente com outros exemplos.

In [34]:
# SISTEMAS TRIANGULARES IFERIORES 

In [49]:
A = np.array([[3, 0, 0, 0], [2, 1, 0, 0], [1, 0, 1, 0], [1, 1, 1, 1]])
b = np.array([4, 2, 4, 2])
print("Minha Função:", SubstituicaoProgressiva(A, b))
print("Scipy       :",sla.solve_triangular(A, b, lower=True))

Minha Função: [ 1.33333333 -0.66666667  2.66666667 -1.33333333]
Scipy       : [ 1.33333333 -0.66666667  2.66666667 -1.33333333]


In [50]:
A = np.array([[4, 5, 5], [6, -1, -2], [0, 2, 2]])
b = np.array([8, 8, 0])
print("Minha Função:", SubstituicaoProgressiva(A, b))
print("Scipy       :",sla.solve_triangular(A, b, lower=True))

Minha Função: [ 2.  4. -4.]
Scipy       : [ 2.  4. -4.]


In [35]:
# SISTEMAS TRIANGULARES SUPERIORES 

In [53]:
A = np.array([[3, 4, -5, 1],[0, 1, 1, -2],[0, 0, 4, -5],[0, 0, 0, 2]])
B = np.array([-10, -1, 3, 2])
print("Minha Função:", SubstituicaoRetroativa(A, B))
print("Scipy       :", sla.solve_triangular(A, B))

Minha Função: [ 1. -1.  2.  1.]
Scipy       : [ 1. -1.  2.  1.]


**Respostas com os mesmo resultados**