**Exercise 1: Existem outras formas de fazer essa importação? Liste-as e discuta suas vantagens e desvantagens.**

In [1]:
import numpy
    # Vantagens: importa todos os módulos de numpy;
    # Desvantagens: escrever o nome numpy em seguindo de um ponto e depois o nome do módulo específico que deseja usar, 
    #               deixando longo e trabalhoso;
    
import numpy as np
    # Ao importar assim, coloca-se um "apelido" para o módulo. Sendo assim, é mais vantajoso quando o nome do pacote é muito grande;
    
from numpy import array
    # Dessa forma, importa-se só o módulo específico no pacote;
    
from numpy import *
    # Dessa forma, importa todos os módulos daquele pacote.

**Exercise 2: Explique os resultados das execuções de todas as células do tutorial, com suas palavras, logo após cada resultado.**

In [2]:
import numpy as np

Importação da biblioteca numpy

In [3]:
arr = np.array([-2, 4.3, 7, 9])

my_tuple = (8, -5, 0, 3.2)
arr2 = np.array(my_tuple)

print('arr = ', arr)
print('arr2 = ', arr2)

arr =  [-2.   4.3  7.   9. ]
arr2 =  [ 8.  -5.   0.   3.2]


É criado um array de 4 elementos, logo em seguida é criado uma tupla de 4 elementos e depois é criado mais um novo array onde é passado como parâmetro a tupla criada.

In [4]:
arr = np.arange(10)
print(arr, '\n')

arr2 = np.arange(1, 32, 2).reshape(4, 4)
print(arr2)

[0 1 2 3 4 5 6 7 8 9] 

[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]
 [25 27 29 31]]


É criado um array de 10 elementos e printado na tela. Depois, é criado uma matriz 4x4 de array de 1 a 32 com passos de 2 e printado na tela.

In [5]:
arr = np.linspace(1, 100, 10) 
print(arr, '\n')

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.] 



Retornar números espaçados uniformemente em um intervalo especificado.

In [7]:
arr2 = np.empty((6,4)) 
print(arr2, '\n')

arr3 = np.eye(4)
print(arr3)

[[7.55075578e-312 7.55075589e-312 7.55075590e-312 7.55075589e-312]
 [7.55075583e-312 7.55075583e-312 7.55075583e-312 7.55075582e-312]
 [7.55075582e-312 7.55075582e-312 7.55075582e-312 7.55075582e-312]
 [7.55075583e-312 7.55075583e-312 7.55075583e-312 7.55075583e-312]
 [7.55075583e-312 7.55075625e-312 7.55075625e-312 7.55075625e-312]
 [7.55075626e-312 7.55075626e-312 7.55075626e-312 7.55075626e-312]] 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


É craido um array vazia com o método empty() onde, normalmente a saída é lixo de memória ou zeros.
Eye cria uma array de duas dimensões com 1 na da diagnoal e 0 nos outros elementos (matriz identidade).

In [9]:
arr = np.zeros(8)
print (arr)

arr2 = np.ones((4,3)) 
print(arr2)

[0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


É criado um array contendo 8 'zeros' e um array com 12 uns no formato 4x3

In [10]:
arr = np.linspace(.5, 50, 10)

print('.shape: ', arr.shape)    
print('.size: ', arr.size)      
print('.dtype: ', arr.dtype)    

.shape:  (10,)
.size:  10
.dtype:  float64


Imprime o formato da array, o tamanho da array e o tipo de dado dos elementos.

In [11]:
print('.ndim: ', arr.ndim)          
print('.itemsize: ', arr.size)      

.ndim:  1
.itemsize:  10


Imprimi o número de dimensões e o tamanho de cada elemento em bytes.

In [12]:
arr = np.arange(1,10)
print('array original: ', arr, '\n')


arr2 = arr.reshape((3,3))
print ('formato 3x3: \n' , arr2, '\n')


array original:  [1 2 3 4 5 6 7 8 9] 

formato 3x3: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 



É criado um array de 9 elementos e logo em seguida é usado o 'reshape()' para muda o formato da array, transformando-a em uma matriz 3x3.

In [13]:
arr.max() # retorna o valor máximo
print(arr.argmax()) # retorna o índice que contém o valor máximo
arr[8] == arr[arr.argmax()]
arr.min() # retorna o mínimo
print(arr.argmin()) # retorna o índice que contém o valor máximo
arr[0] == arr[arr.argmin()]
arr.mean() # retorna a média
arr.std() # retorna o desvio padrão
arr.sum() #retorna a soma de todos os elementos da array

np.sqrt(arr) # retorna um array com a raiz quadrada de cada elemento
np.sin(arr) # retorna um array com o seno de cada elemento
np.cos(arr) # retorna um array com o cosseno de cada elemento
np.exp(arr) # retorna um array com o exponencial cada elemento (e^x)

8
0


array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [14]:
A = np.arange(10)
B = np.arange(10,38,3)

print (' A: ', A, '\n', 'B: ', B)
somar = A + B
subtrair = A - B
dividir = A / B
multiplicar = A * B

print('somar: ', somar )
print('subtrair: ', subtrair )
print('dividir: ', dividir )
print('multiplicar: ', multiplicar)

 A:  [0 1 2 3 4 5 6 7 8 9] 
 B:  [10 13 16 19 22 25 28 31 34 37]
somar:  [10 14 18 22 26 30 34 38 42 46]
subtrair:  [-10 -12 -14 -16 -18 -20 -22 -24 -26 -28]
dividir:  [0.         0.07692308 0.125      0.15789474 0.18181818 0.2
 0.21428571 0.22580645 0.23529412 0.24324324]
multiplicar:  [  0  13  32  57  88 125 168 217 272 333]


O conjunto de códigos acima está somando, subtraindo, dividindo e multiplicando elemento a elemento de dois arrays 'A' e 'B'.

In [15]:
arr = np.arange(1, 10) **2
arr
# acessando o primeiro elemento
print('1º elemento: ', arr[0])    # lembrar que índice começa do 0

# acessando o quinto elemento
print ('5º elemento: ', arr[4])   # O quinto elemento é acessado pelo índice 4
# Em um array de duas dimensões (ou mais) existem duas formas de acessar o índice:

arr = arr.reshape((3,3))
print (arr, '\n')

# Usando colchetes duplos [][]
print ('Acessando o elemento 25: ', arr[1][1])

# Ou minha preferência pessoal - separando índices por vírgula
print ('Acessando o elemento 25: ', arr[1,1])

# acessando o último elemento usando o -1
arr[-1, -1] 
# Para acessar fatias de elementos, usamos o slice [i:i], exemplo

# linha: acessar da linha de índice 0 a linha de índice 2 (excluindo esta) = [0:2]
# coluna: acessar da coluna de índice 0 a coluna de 3 (excluindo esta) = [0:3] - no nosso caso, todas as colunas
print(arr[0:2 , 0:3],'\n')

# outra forma de obter o mesmo resultado é usando [:], que pega todos os elementos
print(arr[0:2 , 0:3])
# Podemos criar uma nova array com slice de outra

arr2 = arr[ : , 1:3]
arr2
# Podemor atribuir novos elementos a nossa array, usando slice

arr[1:2, :] = -99
arr

1º elemento:  1
5º elemento:  25
[[ 1  4  9]
 [16 25 36]
 [49 64 81]] 

Acessando o elemento 25:  25
Acessando o elemento 25:  25
[[ 1  4  9]
 [16 25 36]] 

[[ 1  4  9]
 [16 25 36]]


array([[  1,   4,   9],
       [-99, -99, -99],
       [ 49,  64,  81]], dtype=int32)

**Exercise 3: É curioso notar que todos os elementos de arr se tornaram float após a criação do array, mesmo que nem todos os elementos da lista fossem desse tipo. Por que isso ocorreu? E se um desses elementos fosse um string, qual seria a saída?**

In [16]:
a = np.array(["moabe", "barbosa", "alves"])
a

array(['moabe', 'barbosa', 'alves'], dtype='<U7')

A saída é um array de strings.

**Exercise 4: Quais as diferenças entre os métodos arange e linspace para criar arrays?**

Arange retorna valores uniformemente espaçados dentro de um determinado intervalo. Linspace é muito parecida, mas com uma pequena diferença. Linspace retorna números espaçados de modo uniforme em um intervalo. Dessa forma, dado um ponto inicial e de parada, assim como a quantidade de valores, linspace irá distribuí-los uniformemente para você em uma matriz NumPy. 

**Exercise 5: O método len() é usado para mostrar o tamanho de uma lista. Esse método também funciona para arrays? Explique.**

In [17]:
a = np.array([1,2,3,4])
len(a)

4

Sim, porque o array de numpy é um objeto, logo usando o len(), ele retorna-ra o tamanho.

**Exercise 6: Explique, com suas palavras, o conceito de vetorização do numpy.**

A vetorização do numpy deixa mais eficiente, evitanto loops explicitos e tornando a iterações fiquem mais rápidas.