In [35]:
import scipy.linalg as sla
import numpy as np

### Exercício 1.
* Verifique, refazendo o exemplo acima, se a equação da substituição retroativa, descrita na equação 20, de fato funciona.


In [36]:
A = np.array([[3, 4, -5, 1],[0, 1, 1, -2],[0, 0, 4, -5],[0, 0, 0, 2]])
b = np.array([-10, -1, 3, 2])

In [37]:
sla.solve_triangular(A,b)

array([ 1., -1.,  2.,  1.])

Funciona!

### Exercício 2.
* Faça um programa em Python que calcule a solução de um sistema triangular superior usando substituição retroativa. Para representação das matrizes e vetores use exclusivamente Numpy.

In [38]:
def SubstituicaoRetroativa(A, b):
    n = np.size(b)
    x = np.zeros(n)

    for i in range(n-1, -1, -1):
        soma = 0
        for j in range(i + 1, n):
            soma += A[i][j] * x[j]
        x[i] = (b[i] - soma) / A[i][i]
    return x

A = np.array([[3, 4, -5, 1],[0, 1, 1, -2],[0, 0, 4, -5],[0, 0, 0, 2]])
b = np.array([-10, -1, 3, 2])
print(SubstituicaoRetroativa(A, b))

[ 1. -1.  2.  1.]


### Exercício 3.

* Faça um programa em Python que calcule a solução de um sistema triangular inferior usando substituição progressiva. Para representação das matrizes e vetores use exclusivamente Numpy

In [39]:
def SubstituicaoProgressiva(a, b):
    n = np.size(b)
    x = np.zeros(n)
    for i in range(n):
        soma = 0
        for j in range(n - 1, -1, -1):
            soma += a[i][j] * x[j]

        x[i] = (b[i] - soma) / a[i][i]
    return x



A = np.array([[3, 0, 0, 0], [2, 1, 0, 0], [1, 0, 1, 0], [1, 1, 1, 1]])
b = np.array([4, 2, 4, 2])
print(SubstituicaoProgressiva(A, b))

[ 1.33333333 -0.66666667  2.66666667 -1.33333333]


### Exercício 4. 
* Compare os resultados das implementações de suas funções para a solução de sistemas triangulares com a função do scipy. Os resultados são diferentes? Experimente com outros exemplos.

In [40]:
# SISTEMAS TRIANGULARES IFERIORES 

In [41]:
A = np.array([[3, 0, 0, 0], [2, 1, 0, 0], [1, 0, 1, 0], [1, 1, 1, 1]])
b = np.array([4, 2, 4, 2])
print("Minha Função:", SubstituicaoProgressiva(A, b))
print("Scipy       :",sla.solve_triangular(A, b, lower=True))

Minha Função: [ 1.33333333 -0.66666667  2.66666667 -1.33333333]
Scipy       : [ 1.33333333 -0.66666667  2.66666667 -1.33333333]


In [42]:
A = np.array([[4, 5, 5], [6, -1, -2], [0, 2, 2]])
b = np.array([8, 8, 0])
print("Minha Função:", SubstituicaoProgressiva(A, b))
print("Scipy       :",sla.solve_triangular(A, b, lower=True))

Minha Função: [ 2.  4. -4.]
Scipy       : [ 2.  4. -4.]


In [43]:
# SISTEMAS TRIANGULARES SUPERIORES 

In [44]:
A = np.array([[3, 4, -5, 1],[0, 1, 1, -2],[0, 0, 4, -5],[0, 0, 0, 2]])
B = np.array([-10, -1, 3, 2])
print("Minha Função:", SubstituicaoRetroativa(A, B))
print("Scipy       :", sla.solve_triangular(A, B))

Minha Função: [ 1. -1.  2.  1.]
Scipy       : [ 1. -1.  2.  1.]


**Respostas com os mesmo resultados**

# Execício Complementar

### Exercício 1.1

* Classifique os sistemas abaixo com relação a quantidade e existência de soluções.

### a)

In [45]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([1,1,1])

In [46]:
np.linalg.matrix_rank(A)

2

In [47]:
np.linalg.matrix_rank(np.c_[A,b])

2

### b)

In [48]:
A = np.array([[2,3],[-4,-6]])
b = np.array([10,-10])

In [49]:
np.linalg.matrix_rank(A)

1

In [50]:
np.linalg.matrix_rank(np.c_[A,b])

2

### Exercício 1.2

* Repita o exemplo 3.2 acima, porém fazendo cada passo da execução de forma explícita, comparando como o algoritmo 1.3 e a função sist_lin_tri_sup funcionam. Sugestão: faça isso de forma manuscrita. Ajudará a entender melhor cada passo

In [51]:
def sistLinTriSupExplic(A,b):
    n = len(b)
    x = np.empty(n)
    x[-1] = b[-1]/A[-1,-1]
    for i in range(n-2, -1, -1):
        x[i] = (b[i] - np.sum(A[i,i+1:]*x[i+1:]))/A[i,i]
        print ("x = ",x,'\n')
    return x

In [52]:
A = np.array([[3,4,-5,1],[0,1,1,-2],[0,0,4,-5],[0,0,0,2]])
b = np.array([-10,-1,3,2])
    
sistLinTriSupExplic(A, b)

x =  [2. 3. 2. 1.] 

x =  [ 2. -1.  2.  1.] 

x =  [ 1. -1.  2.  1.] 



array([ 1., -1.,  2.,  1.])